### ISSUE TITLE
On windows 10 device not started

### ISSUE THREAD

**Issue by zen-lab** [mimuz/mimuz-ch55x#5]
in device manager under audio device found "mi:muz-CH" but in properties read :

Failed to start the device. (Code 10)

The I/O device is not configured correctly or the driver configuration parameters are incorrect.

**Comment by tadfmac** [comment]
@zen-lab  
Special thanks your bug report!

We apologize for the inconvenience caused by not being able to test on Windows.
This is probably a misconfiguration of the USB Descriptor, so I fixed it.

Please try the latest version.
